version: '2'
services:
  #======================================================
  # TYPO3
  #======================================================
  typo3:
    container_name: typo3
    build:
      context: .
#      dockerfile: .build/62/Default.Dockerfile # TYPO3 6.2.x Default mode
#      dockerfile: .build/62/Composer.Dockerfile # TYPO3 6.2.x Composer mode
#      dockerfile: .build/76/Default.Dockerfile # TYPO3 7.6.x Default mode
#      dockerfile: .build/76/Composer.Dockerfile # TYPO3 7.6.x Composer mode
#      dockerfile: .build/87/Default.Dockerfile # TYPO3 8.7.x Default mode
#      dockerfile: .build/87/Composer.Dockerfile # TYPO3 8.7.x Composer mode
#      dockerfile: .build/95/Default.Dockerfile # TYPO3 9.5.x Default mode
      dockerfile: .build/95/Composer.Dockerfile # TYPO3 9.5.x Composer mode
    ports:
    - 80:80
    volumes:
    - ./fileadmin:/var/www/html/fileadmin
    - ./typo3conf:/var/www/html/typo3conf
    - ./uploads:/var/www/html/uploads
#  #======================================================
#  # Only PHP
#  #======================================================
#  php:
#    container_name: php
#    build:
#      context: .
#      dockerfile: .build/PHP7/Dockerfile
#      args:
#        MINOR_VERSION: 2
#    ports:
#    - 80:80
#    volumes:
#    - ./app:/var/www/html/app
  #======================================================
  # Database
  #======================================================
  db:
    container_name: db
    image: mariadb:10.1
    command: mysqld --character-set-server=utf8
    ports:
    - 3306:3306
    volumes:
    - .database:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=1234
    - MYSQL_USER=user
    - MYSQL_PASSWORD=1234
    - MYSQL_DATABASE=application